# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jamaica (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  # Pods for jamaica (iOS)

end

target 'jamaica (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jamaica (macOS)

end
